branch-defaults:
  ambassador-shopify-endpoint-CU-1xghu5h:
    application_name: Backend
    environment: ambassadorSite-test
  ambassadorsite:
    environment: ambassadorSite-1
  master:
    environment: ambassadorSiteBackend
    group_suffix: null
  stocktracker:
    environment: Stocktracker-backend-env
global:
  application_name: Stocktracker-backend
  branch: stocktracker
  default_ec2_keyname: aws-eb2
  default_platform: Node.js
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
